opciones_FE:
  - tratamiento_outliers:
      IQR: false
      columnas:
        - Incremento_hombres
        - Incremento_mujeres

  - agrupa:
      valor: Sexo  # Agrupa por Sexo, region o Ambos
      region: Centro  # Solo cuando se agrupa por region: Norte, Occidente, Centro, Sureste


regiones:
  - nombre: Norte
    estados:
      - Baja California
      - Baja California Sur
      - Sonora
      - Chihuahua
      - Coahuila
      - Nuevo León
      - Tamaulipas
      - Sinaloa
      - Durango

  - nombre: Occidente
    estados:
      - Zacatecas
      - Aguascalientes
      - Jalisco
      - Colima
      - Michoacán
      - Nayarit
      - San Luis Potosí
      - Guanajuato
      - Querétaro

  - nombre: Centro
    estados:
      - Ciudad de México
      - México
      - Morelos
      - Tlaxcala
      - Puebla
      - Hidalgo
      - Veracruz

  - nombre: Sureste
    estados:
      - Guerrero
      - Oaxaca
      - Chiapas
      - Tabasco
      - Campeche
      - Yucatán
      - Quintana Roo

