columnas_eliminar:
  - 'No_01'
  - 'No_02'
  - 'No_03'
  - 'No_04'
  - 'Ax_002'
  - 'Padecimiento'
  - 'Cuadro'

renglones_eliminar:
  - Nombre: "Ax_003"
    valor:
      - "Acum."
  - Nombre: "Entidad"
    valor:
      - "TOTAL"


valores_sustituir:
  - Nombre: "Entidad"
    valor_viejo: "Distrito Federal"
    valor_nuevo: "Ciudad de MÃ©xico"