columnas_eliminar:
  - 'Padecimiento'
  - 'Acumulado_anio_anterior'
  - 'Casos_semana'

valores_sustituir:
  - columna_objetivo: "Entidad"
    texto_a_reemplazar: "Distrito Federal"
    texto_sustituto: "Ciudad de MÃ©xico"

registros_eliminar:
  - columna_objetivo: "Semana"
    valor:  53