columnas_eliminar:
  - 'Padecimiento'
  - 'Acumulado_anio_anterior'
  - 'Casos_semana'


renglones_eliminar:

valores_sustituir:
  - columna_objetivo: "Entidad"
    texto_a_reemplazar: "Distrito Federal"
    texto_sustituto: "Ciudad de MÃ©xico"
    
sustituir_cadena:
