reporte_EDA:
  filtro_padecimiento: "${padecimiento.tipo}"
  nombre_reporte: "EDA_${reporte_EDA.filtro_padecimiento}"
  titulo_reporte: "Análisis Exploratorio de Datos"
  subtitulo_reporte: "Padecimiento: ${padecimiento.tipo} (RAW Data)"
  boxplot: False
  bp_comparativa: ""
  violin: True
  max_cols: 33  #limita el número de variables que se visualizarán en la gráfica
  carpeta: "${paths.docs}"
  ruta: "${paths.docs}/${reporte_EDA.nombre_reporte}.pdf"



reporte_clean_dataset:
  nombre_reporte: "EDA_${padecimiento.tipo} (Clean Data)"
  titulo_reporte: "Análisis Exploratorio de Datos"
  subtitulo_reporte: "Padecimiento: ${padecimiento.tipo} (Clean Data)"
  boxplot: True
  bp_comparativa: "Anio"
  violin: False
  max_cols: 34
  carpeta: "${paths.docs}"
  ruta: "${paths.docs}/${reporte_clean_dataset.nombre_reporte}.pdf"



reporte_interim_stage_transformed:
  nombre_reporte: "EDA_${reporte_EDA.filtro_padecimiento} Transformacion"
  titulo_reporte: "Análisis Exploratorio de Datos"
  subtitulo_reporte: "Padecimiento: ${reporte_EDA.filtro_padecimiento} Transformacion (interim)"
  boxplot: False
  bp_comparativa: "Anio"
  violin: False
  max_cols: 34